druid:
  master:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.211.235:3306/gcenter?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abcd1234
    #配置监控统计拦截的 filters,去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat, wall
    #最大活跃数
    maxActive: 200
    #最小活跃数
    minIdle: 10
    #初始化数量
    initialSize: 10
    #最大连接等待超时时间
    maxWait: 60000
    #打开后，增强timeBetweenEvictionRunsMillis的周期性连接检查，minIdle内的空闲连接，每次检查强制验证连接有效性 参考：https://github.com/alibaba/druid/wiki/KeepAlive_cn
    keepAlive: true
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: false
    #maxPoolPreparedStatementPerConnectionSize: 20F
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #空闲连接回收的时间间隔，与testWhileIdle一起使用
    timeBetweenEvictionRunsMillis: 60000
    #连接池空闲连接的有效时间
    minEvictableIdleTimeMillis: 300000
#    MaxEvictableIdleTimeMillis: 500000
    validationQuery: select 1
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false
    #是否自动回收超时连接
    removeAbandoned: false
    #泄露的连接可以被删除的超时值， 单位秒应设置为应用中查询执行最长的时间,单位为秒
    removeAbandonedTimeout: 300
    #关闭abanded连接时输出错误日志
    logAbandoned: false
  slave:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.211.235:3306/gcenter?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abcd1234
    #配置监控统计拦截的 filters,去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat, wall
    #最大活跃数
    maxActive: 200
    #最小活跃数
    minIdle: 10
    #初始化数量
    initialSize: 10
    #最大连接等待超时时间
    maxWait: 60000
    #打开后，增强timeBetweenEvictionRunsMillis的周期性连接检查，minIdle内的空闲连接，每次检查强制验证连接有效性 参考：https://github.com/alibaba/druid/wiki/KeepAlive_cn
    keepAlive: true
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: false
    #maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #空闲连接回收的时间间隔，与testWhileIdle一起使用
    timeBetweenEvictionRunsMillis: 60000
    #连接池空闲连接的有效时间
    minEvictableIdleTimeMillis: 300000
#    MaxEvictableIdleTimeMillis: 500000
    validationQuery: select 1
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false
    #是否自动回收超时连接
    removeAbandoned: false
    #泄露的连接可以被删除的超时值， 单位秒应设置为应用中查询执行最长的时间,单位为秒
    removeAbandonedTimeout: 300
    #关闭abanded连接时输出错误日志
    logAbandoned: false
  monitor:
    username: druid
    password: UxxhvCXjo0Qc+E1drG3l8QMVGM1MRmqvss1iJWJFPwEvM/DBm7R0Qw7roUW5HXFXbs4Wf7v19+kjYoYEGMoHcA==
    #IP白名单 (没有配置或者为空，则允许所有访问)
    allow: ""
    #IP黑名单 (存在共同时，deny优先于allow)
    deny: ""
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJxwPLehC/t0zZri5EE9tjylqMC1hdJIY36MBW+wB7fB+ZoT39TRN3kzJUItTSsjBRXrw7PwYk6PTFw7hEhfD0kCAwEAAQ==

spring:
  redis:
    host: 192.168.211.235
    port: 6379
    password: ""
    database: 6
  jpa:
    database: mysql
    #配置自动建表：update:没有表新建，有表更新操作,控制台显示建表语句
    hibernate:
      ddl-auto: update
    show-sql: true

com:
  zren:
    rocket:
      producer:
        zpoke:
          addr: 192.168.211.235:9876
          group: zpoke_producer_group
          topic: cg_zpoke_out
      consumer:
        zpoke:
          addr: 192.168.211.235:9876
          group: zpoke_consumer_group
          topic: cg_zpoke_in
          listener: zpokeListener